### ISSUE TITLE
Missing pipelines descriptors.json 

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-portal#68]
The file `all_descriptors.json` is not downloaded in the `.cache` repository locally, therefore when I search for pipelines, it gives an error that it cannot find that file

## Expected Behavior

The file `all_descriptors.json` should be downloaded first before launching the application to avoid having the error problem. 

## Current Behavior

![Screenshot_2019-07-16_14-48-34](https://user-images.githubusercontent.com/1534575/61321106-d8961600-a7d8-11e9-8105-53990ffbb9cb.png)

```
Traceback (most recent call last):
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/app/routes.py", line 417, in pipeline_search
    with open(all_desc_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/s/.cache/boutiques/all_descriptors.json'
```

## Environment (optional)

This happened in Ubuntu-based systems. I was able to replicate the bug 3 times. It does not seem to affect Mac users.

**Comment by joeyzhou98** [comment]
@paiva there should be a `logs/update_pipeline_thead.log` file in the root directory, can you let me know if it exists and if so, what it says?

**Comment by paiva** [comment]
Hi @joeyzhou98 thanks for your quick reply. There is a log file, here is the content:

<details>
<summary>Log file </summary>
<br>
```
ERROR:root:An exception occurred in the thread.
Traceback (most recent call last):
  File "/home/s/Work/MNI/CONP/dev/conp-portal/app/threads.py", line 26, in run
    all_descriptors = searcher.search()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/searcher.py", line 45, in search
    results = self.zenodo_search()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/searcher.py", line 62, in zenodo_search
    raise_error(ZenodoError, "Error searching Zenodo", r)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/logger.py", line 7, in raise_error
    .format(message, r.status_code))
boutiques.zenodoHelper.ZenodoError: [ ERROR (500) ] Error searching Zenodo
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
ERROR:root:An exception occurred in the thread.
Traceback (most recent call last):
  File "/home/s/Work/MNI/CONP/dev/conp-portal/app/threads.py", line 26, in run
    all_descriptors = searcher.search()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/searcher.py", line 45, in search
    results = self.zenodo_search()
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/searcher.py", line 62, in zenodo_search
    raise_error(ZenodoError, "Error searching Zenodo", r)
  File "/home/s/Work/MNI/CONP/dev/conp-portal/venv/lib/python3.5/site-packages/boutiques/logger.py", line 7, in raise_error
    .format(message, r.status_code))
boutiques.zenodoHelper.ZenodoError: [ ERROR (500) ] Error searching Zenodo
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 330-855-514
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/css/font-awesome.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/css/custom.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/img/conp.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/js/charts.js HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:48] "[37mGET /static/img/neurolibre-icon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:49] "[37mGET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:39:49] "[37mGET /static/img/conp.ico HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:02] "[37mGET /pipelines HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:03] "[37mGET /static/lib/conp-react/umd/conp-react.js HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:03] "[1m[35mGET /pipeline-search?cursor=0&limit=10&search=&sortComparitor=asc&sortKey=title HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:35] "[37mGET /pipelines HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:36] "[37mGET /static/img/conp.ico HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:36] "[1m[35mGET /pipeline-search?cursor=0&limit=10&search=&sortComparitor=asc&sortKey=title HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:40] "[1m[35mGET /pipeline-search?cursor=0&limit=10&search=&sortComparitor=asc&sortKey=title HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:44] "[37mGET /public HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:47] "[37mGET /pipelines HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:47] "[1m[35mGET /pipeline-search?cursor=0&limit=10&search=&sortComparitor=asc&sortKey=title HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:40:52] "[37mGET /public HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:47:56] "[37mGET /pipelines HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Jul/2019 14:47:57] "[1m[35mGET /pipeline-search?cursor=0&limit=10&search=&sortComparitor=asc&sortKey=title HTTP/1.1[0m" 500 -
```
</details>

**Comment by paiva** [comment]
Thanks @joeyzhou98 for your quick reply. Here is the log: 
[update_pipeline_thread.log](https://github.com/CONP-PCNO/conp-portal/files/3398882/update_pipeline_thread.log)

**Comment by glatard** [comment]
Hi @paiva, can you try to `bosh search` on the portal host?
@joeyzhou98, I guess we should create an empty file if `bosh search` fails, and leave the outdated one in place if it already exists.

**Comment by joeyzhou98** [comment]
Hi @paiva, could you try updating boutiques and then try again, I think @glatard had a similar problem at the beginning too. My boutiques version is 0.5.20.post1

**Comment by paiva** [comment]
Ok, I will try that

Santiago.

**Comment by paiva** [comment]
Changing the version to `boutiques==0.5.20.post1` seems to be solving the problem. I will try to replicate it on a fresh install to confirm. Great suggestion @joeyzhou98

**Comment by glatard** [comment]
@joeyzhou98, I think it now works because Zenodo is back online. It would be nice to make sure that the portal would initialize correctly even when Zenodo is down.

**Comment by paiva** [comment]
@glatard @joeyzhou98 See https://github.com/boutiques/boutiques/pull/534, Xavier found the problem.

**Comment by shots47s** [comment]
@glatard @joeyzhou98  See boutiques/boutiques#536, I made a pull request that fixes another minor bug in this.  Turns out that some of the data is not there if the descriptor has never been downloaded.

**Comment by shots47s** [comment]
Just awaiting Boutiques pull requests to close this issue.

**Comment by glatard** [comment]
@shots47s see my comments in https://github.com/boutiques/boutiques/pull/536, apologies for the delay.

**Comment by shots47s** [comment]
PR merged, so this should be taken care of boutiques/boutiques#536.
